In [1]:
import numpy as np


In [2]:
a=np.array([[1,2,3,4],
            [3,4,5,5]] )

In [3]:
a.sum(axis=1)

array([10, 17])

In [4]:
a.sum(axis=0)

array([4, 6, 8, 9])

In [5]:
print(a)

[[1 2 3 4]
 [3 4 5 5]]


In [6]:
import pandas as pd
import numpy as np

C:\Users\maste\AppData\Local\Temp\ipykernel_22556\2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
